trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.13.2"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run test
    displayName: "npm install and test"